# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Back
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - run: yarn install
      - run: yarn run lint

  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Back
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - run: yarn install
      - run: yarn run build
      - name: API testing
        run: yarn test
        env:
          API_ROUTE_PREFIX: /api/v1
          PORT: 4242

  lint-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Front
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - run: rm -rf node_modules && rm package-lock.json
      - run: npm install
      - run: npm run prettier:check
